export default () => null;
export const Svg = () => null;
export const Circle = () => null;
export const Path = () => null;
export const Rect = () => null;
export const Defs = () => null;
export const LinearGradient = () => null;
export const Stop = () => null;
export const G = () => null;
export const Text = () => null;
