// Complete additions for all 10 locales
const { enNew, frNew } = require('./append-translations.js');

const itNew = {
  'gameover.draw': 'PARITÀ',
  'gameover.youWin': 'HAI VINTO',
  'gameover.defeat': 'SCONFITTA',
  'gameover.place': '{place}° POSTO',
  'gameover.playerWins': '{name} VINCE',
  'gameover.gameOver': 'PARTITA FINITA',
  'gameover.vs': 'vs {name}',
  'gameover.multiplayerSubtitle': '{mode} a {count} giocatori',
  'gameover.ranked': 'Classificata',
  'gameover.unrated': 'Non classificata',
  'gameover.rating': 'PUNTEGGIO',
  'gameover.calculating': 'Calcolo…',
  'gameover.finalRatingNote': 'Il punteggio finale apparirà una volta completato il risultato.',
  'gameover.decidedOnBoard': 'Deciso sulla scacchiera',
  'gameover.youResigned': 'Ti sei arreso',
  'gameover.opponentResigned': "L'avversario si è arreso",
  'gameover.youTimeout': 'Tempo scaduto per te',
  'gameover.opponentTimeout': "Tempo scaduto per l'avversario",
  'gameover.youDisconnect': 'Ti sei disconnesso',
  'gameover.opponentDisconnect': "L'avversario si è disconnesso",
  'gameover.youAfk': 'Abbandono per inattività',
  'gameover.opponentAfk': 'Avversario inattivo',
  'gameover.rematch': 'Rivincita',
  'gameover.newGame': 'Nuova partita',
  'gameover.replay': 'Replay',
  'gameover.analyze': 'Analizza',
  'gameover.viewProfile': 'Vedi profilo',
  'gameover.closeMatch': 'Chiudi partita',
  'gameover.you': '(Tu)',
  'gameover.closeResultA11y': 'Chiudi risultato',

  'result.title': 'Dettagli partita',
  'result.victory': 'Vittoria',
  'result.draw': 'Parità',
  'result.defeat': 'Sconfitta',
  'result.mode': 'Modalità',
  'result.practice': 'Allenamento',
  'result.ratingChange': 'Variazione punteggio',
  'result.done': 'Fine',
  'result.pts': '{count} Punteggio',
  'result.closeA11y': 'Chiudi dettagli partita',

  'achievements.title': 'Obiettivi',
  'achievements.earnedCount': '{earned}/{total}',
  'achievements.earnedBadge': 'SBLOCCATO IL {date}',
  'achievements.comingSoon': 'PROSSIMAMENTE',
  'achievements.new': 'NUOVO',
  'achievements.equipped': 'EQUIPAGGIATO',
  'achievements.equip': 'Equipaggia',
  'achievements.unequip': 'Rimuovi',
  'achievements.ownedBy': 'Posseduto da {count} giocatori',
  'achievements.ownedBySingle': 'Posseduto da 1 giocatore',
  'achievements.notAwarded': 'Non ancora assegnato — si sblocca con più giocatori.',
  'achievements.closeA11y': 'Chiudi obiettivi',
  'achievements.equippedNote': 'Tre obiettivi sbloccati possono essere mostrati sul tuo profilo.',
  'achievements.readOnlyNote': 'Distintivi equipaggiati sul loro profilo.',
  'achievements.prowess': 'Valore',
  'achievements.grind': 'Impegno',
  'achievements.tactics': 'Tattica',
  'achievements.community': 'Comunità',
  'achievements.bronze': 'Bronzo',
  'achievements.silver': 'Argento',
  'achievements.gold': 'Oro',
  'achievements.diamond': 'Diamante',

  'premium.title': 'DuoOrb Premium',
  'premium.bulletAds': 'Nessuna pubblicità',
  'premium.bulletAnalysis': 'Analisi illimitata delle partite',
  'premium.bulletBots': 'Tutti i 6 bot esclusivi',
  'premium.bulletMidnight': 'Tema scacchiera Mezzanotte',
  'premium.bulletCrown': 'Corona Premium sul tuo nome',
  'premium.bestValue': 'Miglior valore',
  'premium.disclosure': 'Annulla quando vuoi in Impostazioni. DuoOrb funziona anche senza Premium.',
  'premium.disclosureRenews': 'Rinnovo automatico fino alla cancellazione.',
  'premium.keepOnAllDevices': 'Mantieni Premium su ogni dispositivo',
  'premium.guestLossWarning': 'Salva prima con Google — gli acquisti sono legati al tuo account.',
  'premium.saveGoogle': 'Salva con Google',
  'premium.continue': 'Continua',
  'premium.availableSoon': 'Disponibile a breve',
  'premium.restoring': 'Ripristino…',
  'premium.restorePurchase': 'Ripristina acquisti',
  'premium.notNow': 'Non ora',

  'reward.title': 'Sblocca l’analisi completa',
  'reward.copy': 'Guarda un breve video per sbloccare l’analisi di questa partita: mosse migliori, errori e grafico.',
  'reward.watch': 'Guarda annuncio',
  'reward.watchA11y': 'Guarda annuncio per sbloccare',
  'reward.goPremium': 'Passa a Premium — illimitato, senza annunci',
  'reward.notNow': 'Non ora',
  'reward.errorUnavailable': 'Gli annunci non sono disponibili ora — controlla la connessione.',
  'reward.errorStore': 'Impossibile salvare lo sblocco — riprova.',
  'reward.errorDismissed': 'Nessun problema — l’analisi resta bloccata.',

  'report.title': 'Segnala @{name}',
  'report.closeA11y': 'Chiudi segnalazione',
  'report.sentTitle': 'Segnalazione inviata',
  'report.sentMessage': 'Grazie — il nostro team esaminerà il giocatore. Il blocco lo nasconde subito.',
  'report.done': 'Fine',
  'report.whatHappened': 'Cosa è successo?',
  'report.details': 'Dettagli (opzionale)',
  'report.placeholder': 'Cosa hanno fatto? Nome, bio, avatar…',
  'report.sending': 'Invio…',
  'report.send': 'Invia segnalazione',
  'report.cancel': 'Annulla',
  'report.sendFailed': 'Impossibile inviare la segnalazione.',
  'report.harassment': 'Molestie o bullismo',
  'report.hate': 'Incitamento all’odio',
  'report.sexual': 'Contenuti sessuali',
  'report.cheating': 'Imbroglio / gioco scorretto',
  'report.spam': 'Spam',
  'report.impersonation': 'Furto d’identità',
  'report.other': 'Altro',

  'connection.noConnection': 'Nessuna connessione',
  'connection.offlineMessage': 'Qualcosa è andato storto, controlla la tua connessione e riprova.',
  'connection.serverMessage': 'Errore sui nostri server. Riprova più tardi.',
  'connection.retry': 'Riprova',
  'connection.youAreOffline': 'Sei offline',
  'connection.sorry': 'Spiacenti',
  'connection.checkInternet': 'Controlla la tua connessione internet.',
  'connection.serverBroke': 'Qualcosa è andato storto sul server. Riprova.',
  'connection.ok': 'OK',

  'challengeToast.joining': 'Accesso alla partita…',
  'challengeToast.gettingReady': 'Preparazione della scacchiera',
  'challengeToast.wantsToPlay': 'vuole giocare con te',
  'challengeToast.accept': 'Accetta',
  'challengeToast.decline': 'Rifiuta',
  'challengeToast.waitingFor': 'In attesa di {name}…',
  'challengeToast.infiniteWalls': '∞ muri',
  'challengeToast.wallsCount': '{count} muri',
  'roomToast.invited': '{name} ti ha invitato in una stanza',
  'roomToast.invitedFriend': 'Un amico ti ha invitato in una stanza',
  'roomToast.declined': 'Invito rifiutato',
  'roomToast.sub': 'Stanza {code} · accetta per entrare',

  'setup.title': 'Imposta Partita',
  'setup.customOnline': 'Partita Online Personalizzata',
  'setup.challengeTitle': 'Sfida {name}',
  'setup.mode': 'Modalità',
  'setup.classic': 'Classica',
  'setup.centerRush': 'Corsa al Centro',
  'setup.race': 'Gara',
  'setup.classicTitle': 'Regole Classiche',
  'setup.classicDesc': 'Il primo orbe che raggiunge il lato opposto vince. Posiziona muri per ostacolare l’avversario.',
  'setup.centerTitle': 'Regole Corsa al Centro',
  'setup.centerDesc': 'Il primo orbe che raggiunge e mantiene il nexus centrale vince.',
  'setup.raceTitle': 'Regole Gara',
  'setup.raceDesc': 'Pura velocità di percorso per attraversare il tabellone.',
  'setup.players': 'Giocatori',
  'setup.freeForAll': 'Tutti contro tutti',
  'setup.playerCount': '{count} Giocatori',
  'setup.aiDifficulty': 'Difficoltà IA',
  'setup.easy': 'Facile',
  'setup.normal': 'Normale',
  'setup.hard': 'Difficile',
  'setup.opponent': 'Avversario',
  'setup.genericAi': 'IA Generica',
  'setup.yourSide': 'Il tuo lato',
  'setup.blue': 'Blu',
  'setup.red': 'Rosso',
  'setup.random': 'Casuale',
  'setup.timeControl': 'Tempo di gioco',
  'setup.walls': 'Muri',
  'setup.walls10': '10 Muri',
  'setup.walls15': '15 Muri',
  'setup.wallsUnlimited': 'Illimitati ∞',
  'setup.playAi': 'Gioca contro IA',
  'setup.sendChallenge': 'Invia Sfida',
  'setup.findCustom': 'Cerca Partita',
  'setup.playLocal': 'Gioca in Locale',

  'profile.title': 'Profilo',
  'profile.playerTitle': 'Profilo Giocatore',
  'profile.rating': 'PUNTEGGIO',
  'profile.winRate': 'VITTORIE',
  'profile.record': '{wins}V · {losses}S',
  'profile.unsavedGuest': 'OSPITE NON SALVATO',
  'profile.joined': 'Iscritto a {date}',
  'profile.achievements': 'OBIETTIVI',
  'profile.earnedCount': '{earned}/{total} ottenuti',
  'profile.equippedCount': '{count} equipaggiati',
  'profile.slot': 'Slot {n}',
  'profile.viewAllAchievements': 'Vedi tutti gli obiettivi',
  'profile.ratingHistory': 'STORICO PUNTEGGIO',
  'profile.ratingHistorySubtitle': 'Progressione 1v1 nelle ultime 20 partite',
  'profile.keepEveryMatch': 'Conserva ogni partita',
  'profile.keepEveryMatchDesc': 'Collega Google per salvare punteggio, amici e storico.',
  'profile.challenge': 'Sfida',
  'profile.addFriend': 'Aggiungi Amico',
  'profile.friends': 'Amici',
  'profile.sent': 'Inviato',
  'profile.unblock': 'Sblocca',
  'profile.block': 'Blocca',
  'profile.report': 'Segnala',
  'profile.blockedNote': 'Bloccato — non incontrerai più questo giocatore.',
  'profile.removeFriendTitle': 'Rimuovere {name}?',
  'profile.removeFriendDesc': 'Non vi vedrete più nei rispettivi elenchi amici.',
  'profile.removing': 'Rimozione…',
  'profile.removeFriend': 'Rimuovi amico',
  'profile.cancel': 'Annulla',
  'profile.headToHead': 'Testa a testa',
  'profile.matchesAgainstYou': 'Partite contro di te',
  'profile.recordLabel': 'Bilancio: ',
  'profile.theyWon': '{name} ha vinto',
  'profile.yourWinRate': 'La tua percentuale di vittoria',
  'profile.youWon': 'Hai vinto tu',
  'profile.recentMatches': 'PARTITE RECENTI',
  'profile.latestGames': 'Ultime {count} partite',
  'profile.noMatches': 'Nessuna partita finora',
  'profile.noMatchesSub': 'Le partite contro questo giocatore appariranno qui.',
  'profile.all': 'Tutte',
  'profile.wins': 'Vittorie',
  'profile.losses': 'Sconfitte',
  'profile.loadMore': 'Carica altro',
  'profile.ptsThisMonth': '{delta} pt questo mese',
  'profile.saveToFriendsTitle': 'Salva il tuo account per aggiungere amici',
  'profile.saveToFriendsMessage': 'Accedi per conservare amici, punteggio e storico su tutti i dispositivi.',
  'profile.notNow': 'Non ora',

  'friends.title': 'Amici',
  'friends.addFriend': 'Aggiungi Amico',
  'friends.searchPlaceholder': 'Cerca amici...',
  'friends.requestsHeader': 'RICHIESTE DI AMICIZIA · {count}',
  'friends.incomingRequest': 'Richiesta di amicizia in arrivo',
  'friends.acceptA11y': 'Accetta richiesta di amicizia',
  'friends.declineA11y': 'Rifiuta richiesta di amicizia',
  'friends.onlineHeader': 'ONLINE · {count}',
  'friends.offlineHeader': 'OFFLINE · {count}',
  'friends.noOnline': 'Nessun amico attualmente online',
  'friends.inMatch': 'In partita',
  'friends.online': 'Online',
  'friends.offline': 'Offline',
  'friends.challenge': 'Sfida',
  'friends.noFriendsTitle': 'Ancora nessun amico',
  'friends.noFriendsSub': 'Cerca giocatori e sfidali in partite tattiche.',
  'friends.findFriends': 'Trova Amici',
  'friends.searchModalPlaceholder': 'Nome utente o ID',
  'friends.searching': 'Ricerca giocatori...',
  'friends.typeMore': 'Digita almeno 3 caratteri per cercare.',
  'friends.needSavingTitle': 'Gli amici richiedono il salvataggio',
  'friends.needSavingMessage': 'I progressi da ospite restano solo su questo dispositivo. Collega Google per giocare con amici.',

  'leaderboard.title': 'Classifica',
  'leaderboard.myRank': 'Il mio rango',
  'leaderboard.you': 'TU',
  'leaderboard.matchesStats': '{games} partite • {winRate}% vittorie',
  'leaderboard.pts': 'pt',
  'leaderboard.noRankingsTitle': 'NESSUNA CLASSIFICA ANCORA',
  'leaderboard.noRankingsDesc': 'Gioca partite classificate per entrare nella classifica globale.',
  'leaderboard.backToTop': 'Torna su',
  'leaderboard.showingCount': 'Visualizzati {count} di {total}',
  'leaderboard.loadMore': 'Carica altro',
  'leaderboard.notRankedTitle': 'NON ANCORA CLASSIFICATO',
  'leaderboard.notRankedDesc': 'Gioca la tua prima partita classificata per apparire in classifica.',
  'leaderboard.playQuick': 'Partita Rapida',
  'leaderboard.guestRankTitle': 'Il tuo rango deve essere salvato',
  'leaderboard.guestRankDesc': 'Collega Google per apparire in classifica e salvare il rango.',

  'history.title': 'Cronologia',
  'history.matches': 'PARTITE',
  'history.wins': 'VITTORIE',
  'history.losses': 'SCONFITTE',
  'history.winRate': 'VITTORIE',
  'history.currentRating': 'PUNTEGGIO ATTUALE',
  'history.onThisDevice': 'SU QUESTO DISPOSITIVO',
  'history.noMatchesRecorded': 'Nessuna partita registrata',
  'history.noMatchesSub': 'Gioca la tua prima partita per vedere lo storico.',
  'history.playNow': 'Gioca Ora',
  'history.loadMore': 'Carica altro',
  'history.loading': 'Caricamento…',
  'history.ranked': 'Classificata',
  'history.practice': 'Allenamento',
};

const deNew = {
  'gameover.draw': 'UNENTSCHIEDEN',
  'gameover.youWin': 'DU GEWINNST',
  'gameover.defeat': 'NIEDERLAGE',
  'gameover.place': '{place}. PLATZ',
  'gameover.playerWins': '{name} GEWINNT',
  'gameover.gameOver': 'SPIEL VORBEI',
  'gameover.vs': 'gg. {name}',
  'gameover.multiplayerSubtitle': '{count}-Spieler {mode}',
  'gameover.ranked': 'Gewertet',
  'gameover.unrated': 'Ungewertet',
  'gameover.rating': 'WERTUNG',
  'gameover.calculating': 'Berechnung…',
  'gameover.finalRatingNote': 'Die endgültige Wertung erscheint nach Auswertung des Spiels.',
  'gameover.decidedOnBoard': 'Auf dem Brett entschieden',
  'gameover.youResigned': 'Du hast aufgegeben',
  'gameover.opponentResigned': 'Gegner hat aufgegeben',
  'gameover.youTimeout': 'Deine Zeit ist abgelaufen',
  'gameover.opponentTimeout': 'Zeit des Gegners abgelaufen',
  'gameover.youDisconnect': 'Du hast die Verbindung getrennt',
  'gameover.opponentDisconnect': 'Gegner hat Verbindung getrennt',
  'gameover.youAfk': 'Verwirkt wegen Inaktivität',
  'gameover.opponentAfk': 'Gegner wegen Inaktivität verwirkt',
  'gameover.rematch': 'Revanche',
  'gameover.newGame': 'Neues Spiel',
  'gameover.replay': 'Wiederholung',
  'gameover.analyze': 'Analysieren',
  'gameover.viewProfile': 'Profil anzeigen',
  'gameover.closeMatch': 'Spiel schließen',
  'gameover.you': '(Du)',
  'gameover.closeResultA11y': 'Ergebnis schließen',

  'result.title': 'Spieldetails',
  'result.victory': 'Sieg',
  'result.draw': 'Unentschieden',
  'result.defeat': 'Niederlage',
  'result.mode': 'Modus',
  'result.practice': 'Übung',
  'result.ratingChange': 'Wertungsänderung',
  'result.done': 'Fertig',
  'result.pts': '{count} Wertung',
  'result.closeA11y': 'Spieldetails schließen',

  'achievements.title': 'Erfolge',
  'achievements.earnedCount': '{earned}/{total}',
  'achievements.earnedBadge': 'FREIGESCHALTET AM {date}',
  'achievements.comingSoon': 'BALD VERFÜGBAR',
  'achievements.new': 'NEU',
  'achievements.equipped': 'AUSGERÜSTET',
  'achievements.equip': 'Ausrüsten',
  'achievements.unequip': 'Ablegen',
  'achievements.ownedBy': 'In Besitz von {count} Spielern',
  'achievements.ownedBySingle': 'In Besitz von 1 Spieler',
  'achievements.notAwarded': 'Noch nicht vergeben — schaltet sich mit mehr Spielern frei.',
  'achievements.closeA11y': 'Erfolge schließen',
  'achievements.equippedNote': 'Drei freigeschaltete Abzeichen können im Profil gezeigt werden.',
  'achievements.readOnlyNote': 'Im Profil ausgerüstete Abzeichen.',
  'achievements.prowess': 'Können',
  'achievements.grind': 'Ausdauer',
  'achievements.tactics': 'Taktik',
  'achievements.community': 'Gemeinschaft',
  'achievements.bronze': 'Bronze',
  'achievements.silver': 'Silber',
  'achievements.gold': 'Gold',
  'achievements.diamond': 'Diamant',

  'premium.title': 'DuoOrb Premium',
  'premium.bulletAds': 'Komplett werbefrei',
  'premium.bulletAnalysis': 'Unbegrenzte Spielanalysen',
  'premium.bulletBots': 'Alle 6 exklusiven Bots',
  'premium.bulletMidnight': 'Mitternachts-Brettdesign',
  'premium.bulletCrown': 'Premium-Krone für deinen Namen',
  'premium.bestValue': 'Bestes Angebot',
  'premium.disclosure': 'Jederzeit in den Einstellungen kündbar. DuoOrb funktioniert auch ohne Premium.',
  'premium.disclosureRenews': 'Verlängert sich automatisch bis zur Kündigung.',
  'premium.keepOnAllDevices': 'Premium auf allen Geräten behalten',
  'premium.guestLossWarning': 'Zuerst mit Google sichern — Käufe hängen an deinem Konto.',
  'premium.saveGoogle': 'Mit Google sichern',
  'premium.continue': 'Weiter',
  'premium.availableSoon': 'Bald verfügbar',
  'premium.restoring': 'Wiederherstellen…',
  'premium.restorePurchase': 'Käufe wiederherstellen',
  'premium.notNow': 'Nicht jetzt',

  'reward.title': 'Komplette Analyse freischalten',
  'reward.copy': 'Kurzes Video ansehen, um die Analyse freizuschalten — beste Züge, Fehler und Sieggraph.',
  'reward.watch': 'Werbung ansehen',
  'reward.watchA11y': 'Werbung für Analyse ansehen',
  'reward.goPremium': 'Premium holen — unbegrenzt, werbefrei',
  'reward.notNow': 'Nicht jetzt',
  'reward.errorUnavailable': 'Werbung derzeit nicht verfügbar — Verbindung prüfen.',
  'reward.errorStore': 'Freischaltung konnte nicht gespeichert werden.',
  'reward.errorDismissed': 'Kein Problem — Analyse bleibt gesperrt.',

  'report.title': '@{name} melden',
  'report.closeA11y': 'Meldung schließen',
  'report.sentTitle': 'Meldung gesendet',
  'report.sentMessage': 'Danke — unser Team prüft diesen Spieler. Blockieren blendet ihn sofort aus.',
  'report.done': 'Fertig',
  'report.whatHappened': 'Was ist passiert?',
  'report.details': 'Details (optional)',
  'report.placeholder': 'Was wurde getan? Name, Bio, Avatar…',
  'report.sending': 'Senden…',
  'report.send': 'Meldung senden',
  'report.cancel': 'Abbrechen',
  'report.sendFailed': 'Meldung konnte nicht gesendet werden.',
  'report.harassment': 'Belästigung oder Mobbing',
  'report.hate': 'Hassrede',
  'report.sexual': 'Sexuelle Inhalte',
  'report.cheating': 'Cheating / Unfaires Spiel',
  'report.spam': 'Spam',
  'report.impersonation': 'Identitätstäuschung',
  'report.other': 'Etwas anderes',

  'connection.noConnection': 'Keine Verbindung',
  'connection.offlineMessage': 'Etwas ist schiefgelaufen. Bitte prüfe deine Internetverbindung.',
  'connection.serverMessage': 'Fehler auf unseren Servern. Bitte erneut versuchen.',
  'connection.retry': 'Wiederholen',
  'connection.youAreOffline': 'Du bist offline',
  'connection.sorry': 'Entschuldigung',
  'connection.checkInternet': 'Bitte prüfe deine Internetverbindung.',
  'connection.serverBroke': 'Serverproblem aufgetreten. Bitte erneut versuchen.',
  'connection.ok': 'OK',

  'challengeToast.joining': 'Spiel beitreten…',
  'challengeToast.gettingReady': 'Brett wird vorbereitet',
  'challengeToast.wantsToPlay': 'möchte gegen dich spielen',
  'challengeToast.accept': 'Annehmen',
  'challengeToast.decline': 'Ablehnen',
  'challengeToast.waitingFor': 'Warten auf {name}…',
  'challengeToast.infiniteWalls': '∞ Wände',
  'challengeToast.wallsCount': '{count} Wände',
  'roomToast.invited': '{name} hat dich in einen Raum eingeladen',
  'roomToast.invitedFriend': 'Ein Freund hat dich in einen Raum eingeladen',
  'roomToast.declined': 'Raumeinladung abgelehnt',
  'roomToast.sub': 'Raum {code} · annehmen zum Beitreten',

  'setup.title': 'Spielaufbau',
  'setup.customOnline': 'Eigenes Online-Spiel',
  'setup.challengeTitle': '{name} herausfordern',
  'setup.mode': 'Modus',
  'setup.classic': 'Klassisch',
  'setup.centerRush': 'Zentrumssturm',
  'setup.race': 'Rennen',
  'setup.classicTitle': 'Klassische Regeln',
  'setup.classicDesc': 'Die erste Kugel am gegenüberliegenden Rand gewinnt. Platziere Wände, um den Gegner abzulenken.',
  'setup.centerTitle': 'Zentrumssturm-Regeln',
  'setup.centerDesc': 'Erste Kugel, die den zentralen Nexus erreicht und hält, gewinnt.',
  'setup.raceTitle': 'Renn-Regeln',
  'setup.raceDesc': 'Reines Geschwindigkeitsrennen zur gegenüberliegenden Kante.',
  'setup.players': 'Spieler',
  'setup.freeForAll': 'Jeder gegen jeden',
  'setup.playerCount': '{count} Spieler',
  'setup.aiDifficulty': 'KI-Schwierigkeit',
  'setup.easy': 'Einfach',
  'setup.normal': 'Normal',
  'setup.hard': 'Schwer',
  'setup.opponent': 'Gegner',
  'setup.genericAi': 'Standard-KI',
  'setup.yourSide': 'Deine Seite',
  'setup.blue': 'Blau',
  'setup.red': 'Rot',
  'setup.random': 'Zufällig',
  'setup.timeControl': 'Bedenkzeit',
  'setup.walls': 'Wände',
  'setup.walls10': '10 Wände',
  'setup.walls15': '15 Wände',
  'setup.wallsUnlimited': 'Unbegrenzt ∞',
  'setup.playAi': 'Gegen KI spielen',
  'setup.sendChallenge': 'Herausforderung senden',
  'setup.findCustom': 'Spiel suchen',
  'setup.playLocal': 'Lokal spielen',

  'profile.title': 'Profil',
  'profile.playerTitle': 'Spielerprofil',
  'profile.rating': 'WERTUNG',
  'profile.winRate': 'SIEGQUOTE',
  'profile.record': '{wins}S · {losses}N',
  'profile.unsavedGuest': 'UNGESPEICHERTER GAST',
  'profile.joined': 'Beigetreten {date}',
  'profile.achievements': 'ERFOLGE',
  'profile.earnedCount': '{earned}/{total} erreicht',
  'profile.equippedCount': '{count} ausgerüstet',
  'profile.slot': 'Platz {n}',
  'profile.viewAllAchievements': 'Alle Erfolge anzeigen',
  'profile.ratingHistory': 'WERTUNGSVERLAUF',
  'profile.ratingHistorySubtitle': '1v1-Entwicklung über die letzten 20 Spiele',
  'profile.keepEveryMatch': 'Jedes Spiel behalten',
  'profile.keepEveryMatchDesc': 'Google verknüpfen, um Wertung, Freunde und Verlauf zu sichern.',
  'profile.challenge': 'Herausfordern',
  'profile.addFriend': 'Freund hinzufügen',
  'profile.friends': 'Freunde',
  'profile.sent': 'Gesendet',
  'profile.unblock': 'Entsperren',
  'profile.block': 'Blockieren',
  'profile.report': 'Melden',
  'profile.blockedNote': 'Blockiert — keine Spiele oder Anfragen mehr von diesem Spieler.',
  'profile.removeFriendTitle': '{name} entfernen?',
  'profile.removeFriendDesc': 'Ihr werdet nicht mehr in euren Freundeslisten angezeigt.',
  'profile.removing': 'Entfernen…',
  'profile.removeFriend': 'Freund entfernen',
  'profile.cancel': 'Abbrechen',
  'profile.headToHead': 'Direktvergleich',
  'profile.matchesAgainstYou': 'Spiele gegen dich',
  'profile.recordLabel': 'Bilanz: ',
  'profile.theyWon': '{name} hat gewonnen',
  'profile.yourWinRate': 'Deine Siegquote',
  'profile.youWon': 'Du hast gewonnen',
  'profile.recentMatches': 'LETZTE SPIELE',
  'profile.latestGames': 'Letzte {count} Spiele',
  'profile.noMatches': 'Noch keine Spiele',
  'profile.noMatchesSub': 'Spiele gegen diesen Spieler erscheinen hier.',
  'profile.all': 'Alle',
  'profile.wins': 'Siege',
  'profile.losses': 'Niederlagen',
  'profile.loadMore': 'Mehr laden',
  'profile.ptsThisMonth': '{delta} Pkt. diesen Monat',
  'profile.saveToFriendsTitle': 'Konto sichern, um Freunde hinzuzufügen',
  'profile.saveToFriendsMessage': 'Anmelden, um Freunde, Wertung und Spielverlauf geräteübergreifend zu behalten.',
  'profile.notNow': 'Nicht jetzt',

  'friends.title': 'Freunde',
  'friends.addFriend': 'Freund hinzufügen',
  'friends.searchPlaceholder': 'Freunde suchen...',
  'friends.requestsHeader': 'FREUNDSCHAFTSANFRAGEN · {count}',
  'friends.incomingRequest': 'Eingehende Freundschaftsanfrage',
  'friends.acceptA11y': 'Freundschaftsanfrage annehmen',
  'friends.declineA11y': 'Freundschaftsanfrage ablehnen',
  'friends.onlineHeader': 'ONLINE · {count}',
  'friends.offlineHeader': 'OFFLINE · {count}',
  'friends.noOnline': 'Zurzeit keine Freunde online',
  'friends.inMatch': 'Im Spiel',
  'friends.online': 'Online',
  'friends.offline': 'Offline',
  'friends.challenge': 'Herausfordern',
  'friends.noFriendsTitle': 'Noch keine Freunde',
  'friends.noFriendsSub': 'Suche nach Spielern und fordere sie heraus.',
  'friends.findFriends': 'Freunde finden',
  'friends.searchModalPlaceholder': 'Benutzername oder ID',
  'friends.searching': 'Spieler werden gesucht...',
  'friends.typeMore': 'Mindestens 3 Zeichen eingeben.',
  'friends.needSavingTitle': 'Freunde erfordern ein Konto',
  'friends.needSavingMessage': 'Gastfortschritt verbleibt nur auf diesem Gerät. Verknüpfe Google, um Freunde hinzuzufügen.',

  'leaderboard.title': 'Bestenliste',
  'leaderboard.myRank': 'Mein Rang',
  'leaderboard.you': 'DU',
  'leaderboard.matchesStats': '{games} Spiele • {winRate}% Siegquote',
  'leaderboard.pts': 'Pkt.',
  'leaderboard.noRankingsTitle': 'NOCH KEINE RANGLISTE',
  'leaderboard.noRankingsDesc': 'Spiele gewertete Matches, um dich für die globale Bestenliste zu qualifizieren.',
  'leaderboard.backToTop': 'Nach oben',
  'leaderboard.showingCount': 'Zeige {count} von {total}',
  'leaderboard.loadMore': 'Mehr laden',
  'leaderboard.notRankedTitle': 'NOCH NICHT GEWERTET',
  'leaderboard.notRankedDesc': 'Spiele dein erstes gewertetes Spiel, um in der Bestenliste zu erscheinen.',
  'leaderboard.playQuick': 'Schnellspiel',
  'leaderboard.guestRankTitle': 'Dein Rang muss gesichert werden',
  'leaderboard.guestRankDesc': 'Verknüpfe Google, um in der Bestenliste zu erscheinen.',

  'history.title': 'Verlauf',
  'history.matches': 'SPIELE',
  'history.wins': 'SIEGE',
  'history.losses': 'NIEDERLAGEN',
  'history.winRate': 'SIEGQUOTE',
  'history.currentRating': 'AKTUELLE WERTUNG',
  'history.onThisDevice': 'AUF DIESEM GERÄT',
  'history.noMatchesRecorded': 'Keine Spiele aufgezeichnet',
  'history.noMatchesSub': 'Spiele dein erstes Spiel, um deinen Verlauf zu sehen.',
  'history.playNow': 'Jetzt spielen',
  'history.loadMore': 'Mehr laden',
  'history.loading': 'Laden…',
  'history.ranked': 'Gewertet',
  'history.practice': 'Übung',
};

const { esNew, ptBRNew } = require('./locales-es-pt.js');
const { trNew, plNew } = require('./locales-tr-pl.js');
const { idNew, arNew } = require('./locales-id-ar.js');

module.exports = {
  en: enNew,
  fr: frNew,
  it: itNew,
  de: deNew,
  es: esNew,
  ptBR: ptBRNew,
  tr: trNew,
  pl: plNew,
  id: idNew,
  ar: arNew,
};
